### ISSUE TITLE
Upgrade to g 4

### ISSUE THREAD

**Issue by lferran** [plone/guillotina_s3storage#1]
setup.py should also be adapted right?

To something like
```
    install_requires=[
        'setuptools',
        'guillotina>=4.0.0,<5.0.0',
        'aiohttp<4.0.0',
        'boto3',
        ...
    ],
```

**Comment by vangheem** [comment]
I'm not sure why we have the restriction there but definitely go ahead and update/test.

**Comment by vangheem** [comment]
I think the real reason is the change in http exception and response objects.
